version: '3.8'

services:
  app:
    container_name: cryp-wallet
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports: [3002:3002]
    restart: always
